### ISSUE TITLE
默认为本地存储策略

### ISSUE THREAD

**Issue by Gahotx** [hellodk34/picgo-plugin-lankong#1]
如题，希望可以加一个自定义存储策略的功能
![image](https://user-images.githubusercontent.com/53534938/160232473-17273053-351e-4539-aad5-35e7ace7e6a0.png)

**Comment by hellodk34** [comment]
感谢提 issue。

![20220326185939](https://cdn.dogimg.com/pic/2022/03/26/623ef21a78db4.png)

已更新至 `v1.0.3`，不过我没有可用的存储策略ID，还请麻烦你帮我测试一下，感谢🙏🏻

**Comment by Gahotx** [comment]
感谢大佬，我测试了，没有问题😁
