### ISSUE TITLE
Typora使用picGo-Core(commandline)的方法

### ISSUE THREAD

**Issue by saiveen1** [hellodk34/picgo-plugin-lankong#10]
感谢作者提供插件，下面是Typora使用picGo命令行的方法（调用APP有点烦），应该有人用得到

**找到picgo-core**

- `windows` 一般在`C:\Users\用户名\AppData\Roaming\Typora\picgo\win64\`文件夹，文件名为`picgo.exe`；
- `linux` 一般在`~/.config/Typora/picgo/linux/`文件夹，文件名为`picgo`；

**接下来执行命令：**
- `windows` 执行`picgo.exe install lankong`；
- `linux` `home`目录下执行`./.config/Typora/picgo/linux/picgo install gitee-uploader`；

然后配置文件
```json
{
  "picBed": {
  	"current": "lankong",
  	"uploader": "lankong",
  	"lankong": {
  		"lskyProVersion": "", //兰空版本V1,V2
  		"server": "", //示例: https://example.com
  		"token": "", //认证 token 信息
  		"strategyId": "", //选填, V1以及V2使用默认存储策略时请留空
  		"ignoreCertErr": "", //是否忽略证书错误, 如果上传失败提示证书过期请设为true
  		"syncDelete": "" //是否同步删除，只支持V2
  	}
  },
  "picgoPlugins": {
  	"picgo-plugin-lankong": true,
  }
}
```

**Comment by hellodk34** [comment]
我还没用过 picgo-core command line，很感谢你的补充。感觉使用习惯了会很顺手。
