### ISSUE TITLE
能不能出一个PicGo-Core(command line) 中的配置方法教程呢

### ISSUE THREAD

**Issue by For-Light** [hellodk34/picgo-plugin-lankong#11]
能不能出一个PicGo-Core(command line) 中的配置方法教程呢

**Comment by hellodk34** [comment]
#10 看看这个是否有帮助 :)

**Comment by hellodk34** [comment]
@For-Light
@saiveen1

刚刚我第一次试用 command line，其实感觉没多方便，上传成功后的图片 link 甚至不能自动写入剪贴板，还得手动复制。gui 明显更加方便: 直接截图，然后按快捷键 `control/command + shift + p`，上传成功后 markdown style 的图片 url 自动写入剪贴板，在需要的地方直接粘贴即可。

下面详细说一下 PicGo-Core command line 的使用方法。

首先这是官方文档 https://picgo.github.io/PicGo-Core-Doc/zh/guide/commands.html 有什么不清楚的先看官方文档。

确保你的 win/mac/linux 安装了 node.js，然后安装了 npm，推荐安装 yarn 进行包管理，然后通过命令 `yarn global add picgo` 安装 picgo 核心程序。

如果你在 windows 下执行 `picgo -h` 遇到 command not found 之类的报错，请检查 `PATH`，一般是 yarn 的 bin 路径没有被添加到环境变量 `PATH` 中导致，我写过这篇文章可参考: [Windows 10 通过 yarn 全局安装了其他包但是无法执行包的指令报错“command not found” 解决办法](https://hellodk.cn/post/954) 

确保执行 `picgo -v` 有版本号输出，比如

```
$ picgo -v
1.5.0-alpha.0
```

那么就可以进行下一步操作了。

## 安装 lankong

```
$ picgo install lankong
npm notice created a lockfile as package-lock.json. You should commit this file.
+ picgo-plugin-lankong@1.0.6
added 1 package from 1 contributor and audited 1 package in 0.977s
found 0 vulnerabilities
```

## 配置 picgo-core 使用的 uploader 和 transformer

```
$ picgo use
? Use an uploader lankong
? Use a transformer path
? Use plugins picgo-plugin-lankong
[PicGo SUCCESS]: Configure config successfully!
```

- uploader 选 `lankong`
- transformer 选 `path`
- 这是交互式命令行程序，我们在终端输入 `picgo use` 回车然后操作(选择或者输入)即可

## 设置 uploader

```
$ picgo set uploader
? Choose a(n) uploader lankong
? Choose a version V2
? 示例: https://example.com https://image.example.com
? 认证 token 信息 Bearer x|xxx
? 选填, V1以及V2使用默认存储策略时请留空
? 是否忽略证书错误, 如果上传失败提示证书过期请设为true No
? 是否同步删除，只支持V2 Yes
[PicGo SUCCESS]: Configure config successfully!
```

## 上传

使用命令行 `picgo u` 上传

```
# picgo u 是 picgo upload 的简写，两个命令都可

# 上传本地文件
$ picgo u ./bbb.png
[PicGo INFO]: Before transform
[PicGo INFO]: Transforming... Current transformer is [path]
[PicGo INFO]: Before upload
[PicGo INFO]: Uploading... Current uploader is [lankong]
[PicGo SUCCESS]:
https://image.example.com/xxx.png

# 上传当前剪贴板里的第一张图片
$ picgo u
[PicGo INFO]: Before transform
[PicGo INFO]: Transforming... Current transformer is [path]
[PicGo INFO]: Before upload
[PicGo INFO]: Uploading... Current uploader is [lankong]
[PicGo SUCCESS]:
https://image.example.com/xxx.png
```

![20220513110112](https://img.940304.xyz/i/2022/05/13/627dc9fa67099.png)

ok, 希望有帮助。

**Comment by hellodk34** [comment]
> 刚刚我第一次试用 command line，其实感觉没多方便，上传成功后的图片 link 甚至不能自动写入剪贴板，还得手动复制。gui 明显更加方便: 直接截图，然后按快捷键 control/command + shift + p，上传成功后 markdown style 的图片 url 自动写入剪贴板，在需要的地方直接粘贴即可。

关于我上面说的这一段，由于我不太使用 Typora，所以不知道 Typora 的流程是否是更适合 command line。

**Comment by For-Light** [comment]
感谢大佬百忙中抽出时间写的教程，我用的是 Typora ，主要是不想开太多后台，我先试试看，不行的话还是老老实实 GUI，再次感谢大佬

**Comment by For-Light** [comment]
原来closed issue里面就有。。。实在不好意思有麻烦大佬一遍，没注意看，哈哈

**Comment by hellodk34** [comment]
@For-Light 没关系没关系，typora 应该是更适合用命令行，我这种 vscode 用户感觉 gui 更方便~

**Comment by saiveen1** [comment]
@hellodk34 不好意思未及时看到，啊😂，不知道其他软件什么上传逻辑，typora 是可以设置自动上传直接返回图片地址的，所以GUI 其实是个累赘，但也不是不可以用，如@For-Light 所言多了个后台
如下为效果图，然后附上教程。
再次感谢作者提供的插件，听我说谢谢你，因为有你，温暖了四季。
![Typora_RKMf2tUwrr](https://user-images.githubusercontent.com/34472475/168442080-dd593b4d-2445-4219-b597-031ea8c693f2.gif)

# 如何在Typora中使用兰空图床
## 安装lankong 插件
参考前半段Typora 如何安装插件，#10 
## 使用Picgo命令行
文件 > 首选项 > 图像 > 上传服务 > PicGo-Core(command line)
## 配置文件
如有不懂，请参考[作者Readme](https://github.com/hellodk34/picgo-plugin-lankong/blob/main/README.md#3-%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95)
```JSON
{
  "picBed": {
  	"current": "lankong",
  	"uploader": "lankong",
  	"lankong": {
  		"lskyProVersion": "", //兰空版本V1,V2
  		"server": "", //示例: https://example.com
  		"token": "", //认证 token 信息
  		"strategyId": "", //选填, V1以及V2使用默认存储策略时请留空
  		"ignoreCertErr": "", //是否忽略证书错误, 如果上传失败提示证书过期请设为true
  		"syncDelete": "" //是否同步删除，只支持V2
  	}
  },
  "picgoPlugins": {
  	"picgo-plugin-lankong": true,
  }
}
```
完成后可点击`验证图片上传选项`进行测试，测试完成后，选择插入图片时手动上传即可实现自动上传操作。
![image](https://user-images.githubusercontent.com/34472475/168443112-d691cca1-b365-40ae-b6bc-f415266ec1d4.png)

**Comment by xiaozhang959** [comment]
感谢大佬们，百度找了好久没找到，在这找到了。感谢感谢

**Comment by ReRokutosei** [comment]
>补充一个与typora设置相关的：

1.在命令提示符通过命令 yarn global add picgo 安装 picgo 核心程序之后，按照楼上大佬说的配置好环境变量。
2.接着设置好图床的各项参数。
3.打开typora-设置-图像-上传服务设定：
    这里不选typora提供的，我们选择自定义命令，然后命令框输入`"C:\Users\{改为你的用户名}\AppData\Local\Yarn\Data\global\node_modules\.bin\picgo.cmd" u` 这样就OK了

>这个自定义命令我试了直接写`picgo u`或`picgo upload`，typora都是报错，但是在cmd测试又是正常的，这就很奇怪
