### ISSUE TITLE
上传失败

### ISSUE THREAD

**Issue by GC-ZF** [hellodk34/picgo-plugin-lankong#13]
麻烦问一下，这个是哪里配置不对么？
## lankong版本
![image](https://user-images.githubusercontent.com/94956933/178675754-cac73579-a3a8-4e04-b90c-06e1c85d68bf.png)

## lankong插件配置
![image](https://user-images.githubusercontent.com/94956933/178675671-01a56d0d-c957-4fee-b84e-75d7b74bd9c3.png)

## 错误日志
![image](https://user-images.githubusercontent.com/94956933/178675521-344cbf36-8276-4c47-9ce2-f450fafe69b5.png)

**Comment by GC-ZF** [comment]
## 拼接token
![image](https://user-images.githubusercontent.com/94956933/178682146-aa1c7782-4e09-492e-bc64-f8ec23faaa13.png)

## 日志
![image](https://user-images.githubusercontent.com/94956933/178682088-6bab2288-6e1c-48ec-9188-5d6bd51d0bdf.png)

**Comment by hellodk34** [comment]
@GC-ZF 忽略证书错误的开关在证书没有问题的情况下请不要打开，打开后每次请求会带上一个代理，反而降低了性能（虽然很微小）。

**Comment by GC-ZF** [comment]
> @GC-ZF 忽略证书错误的开关在证书没有问题的情况下请不要打开，打开后每次请求会带上一个代理，反而降低了性能（虽然很微小）。

嗯，十分感谢
