### ISSUE TITLE
设置auth token后，仍被视为游客上传

### ISSUE THREAD

**Issue by ShiinaRinne** [hellodk34/picgo-plugin-lankong#14]
![image](https://user-images.githubusercontent.com/45081750/183284832-732da753-26de-47d4-8575-12bc4fce008a.png)

![image](https://user-images.githubusercontent.com/45081750/183284828-3423f73d-bb5e-411f-bf6a-7f395d9b2939.png)

![image](https://user-images.githubusercontent.com/45081750/183284821-2fa05ae6-3643-43f7-ae49-1d28d6e05026.png)

感觉有可能是安装时候出错了，目前的url和api都必须带`/index.php`才可以正确访问，例如加 `xx.com/index.php/images`

兰空版本为v2
picgo 2.3.1-beta.4
兰空插件 1.0.6

**Comment by hellodk34** [comment]
我看你设置了策略 ID，是在兰空挂载了其他云存储么，那个策略 ID 如果用的默认本地存储的话就别填了。

如果是安装问题可以试试 docker 安装（或者换一个镜像）？  https://hub.docker.com/r/dko0/lsky-pro （毛遂自荐了）

**Comment by ShiinaRinne** [comment]
对，挂了个别的oss，我现在试试docker

**Comment by hellodk34** [comment]
ok，等你的反馈。

**Comment by ShiinaRinne** [comment]
解决了!我重买了个centos的服务器安装之后就可以了,问题可能就在windows服务器的伪静态吧
