### ISSUE TITLE
新增默认相册选项

### ISSUE THREAD

**Issue by timeance** [hellodk34/picgo-plugin-lankong#15]
感谢大佬的插件，上传图片真的太方便了

希望能新增选择相册的功能，强迫症在上传东西的时候习惯齐齐整整（虽然图床的相册功能好像用处不大）

![](https://i.peo.pw/2022/08/18/62fe1ae292138.png)

**Comment by hellodk34** [comment]
这个我之前想做来着，但是 Lsky Pro V2 没有提供上传到相册的 API（只有上传到指定存储策略的），所以咱们也无法实现。

**Comment by hellodk34** [comment]
![42d0e0ffb1851a76c18ad1d19d15eb1a.jpg](https://img.gejiba.com/images/42d0e0ffb1851a76c18ad1d19d15eb1a.jpg)

刚看了一下好像有更新了。

```
Lsky Pro V 2.1

1.8 MB

发布于 2022-08-17 13:40
```

如果有的话，会做的。

**Comment by hellodk34** [comment]
- 升级失败
- 然后又无法查找到更新
- 后面更新到最新有 api 了再来做

![17ce7e9f8889b60fadc7f3e096eb687f.jpg](https://img.gejiba.com/images/17ce7e9f8889b60fadc7f3e096eb687f.jpg)

**Comment by hellodk34** [comment]
@timeance 请问你的是兰空企业版吗，我的普通版升级到了 `2.1` 上传接口还是没有上传到相册的能力。

**Comment by hellodk34** [comment]
已开发完成，欢迎测试。请到 PicGo `插件设置` 中更新到最新版 1.1.3.

![lankong新设置](https://image.940304.xyz/i/2022/08/20/630092cd733c5.jpg)

**Comment by timeance** [comment]
> 已开发完成，欢迎测试。请到 PicGo `插件设置` 中更新到最新版 1.1.3.
> 
太感谢了！刚刚试了一下工作的很好。请大佬喝阔乐 :>

**Comment by hellodk34** [comment]
@timeance 太感动了！谢谢你请的快乐水😭️，很好喝。

**Comment by Ton-yi** [comment]
Lsky 的相册ID在哪查看？
刚搭建Lsky 新建了一个相册，初试 “0” “1” “2”都失败了

**Comment by hellodk34** [comment]
> Lsky 的相册ID在哪查看？ 刚搭建Lsky 新建了一个相册，初试 “0” “1” “2”都失败了

@Ton-yi  开源免费版的没有相册的管理。要想知道相册 id 只能通过接口 url 或者 request payload

![禁言两小时-兰空图床](https://user-images.githubusercontent.com/28612780/201559063-ea875462-d9b5-43fe-804b-b5150bac9089.jpg)

**Comment by hellodk34** [comment]
> Lsky 的相册ID在哪查看？ 刚搭建Lsky 新建了一个相册，初试 “0” “1” “2”都失败了

@Ton-yi  在设置里设置【默认相册】功能，可以查看到相册 id。

**Comment by Ton-yi** [comment]
感谢回答，我api获取相册id确实为1，但lankong无法使用
之后尝试新相册id2也不行

只能上传至Lsky内默认上传相册的所设置的相册（包括未选取）


我使用的是[halcyonazure/lsky-pro-docker](https://registry.hub.docker.com/r/halcyonazure/lsky-pro-docker/) 用SQLite创建的Lsky，之后新建测试账号也失败了

**Comment by hellodk34** [comment]
感觉是你的使用方法有问题。我看这个功能是正常的。
