### ISSUE TITLE
token 认证的问题

### ISSUE THREAD

**Issue by theingz** [hellodk34/picgo-plugin-lankong#18]
大佬，我自己也用 docker 搭建了兰空图床，使用的是你的picgo插件，但是图片上传不了，查看代码，在index.ts 68行发现你认证的token拼接使用的是
```
'Authorization': token || undefined
```
这样的拼接似乎有问题，图片上传不了
![image](https://user-images.githubusercontent.com/39908112/204746615-3b7d507f-ed6c-409b-9390-06dc2f3950ad.png)

是否可以改成 Bearer 进行拼接呢？
比如
```
'Authorization': `Bearer ${token}`
```
或者我提一个pr？？

**Comment by hellodk34** [comment]
@theingz 哦哦，这点我在 readme 里写了，让用户自己拼接的。。让用户拿到 token 的值，再在前面加上 `Bearer ` 填上。

你这样也挺好，但是我这样做的初衷是与官方的 `Authorization` 值保持一致。

**Comment by theingz** [comment]
感谢！！！
