### ISSUE TITLE
在picgo的相册中无法删除图床里的图片

### ISSUE THREAD

**Issue by tonywang1201** [hellodk34/picgo-plugin-lankong#2]
在picgo的相册里删除图片后，lsky图床里对应的照片没有被删除。官方的接口是有删除功能的，请问插件是否支持。很感谢您写出这个好插件，希望尽快得到回复。

**Comment by hellodk34** [comment]
确实是这样的，虽然 Lsky Pro V1 和 V2 都有提供删除图片的 API。在 PicGo 相册删除本地图片信息时同步删除 Lsky Pro 图床上的图片是比较困难而且比较麻烦。

我的建议是如果需要删除图片，直接在 Lsky Pro 图床中操作。PicGo 的目的是方便 Markdown 写作的人快速获得图片 markdown 格式的字符串，实际上他的图片管理只是在本地进行数据的操作，默认不会同步到远端。

[关于同步删除可以查看一下官方回应](https://gitter.im/picgo-all/PicGo?at=5eb12bfd347bd61630570996)

![20220327153154](https://cdn.dogimg.com/pic/2022/03/27/624012e7b84ae.png)

兰空 V1 的删除 API

![20220327153915](https://cdn.dogimg.com/pic/2022/03/27/624014a109501.png)
> 此处的图片 ID 在图片上传接口中并没有返回，需要遍历所有图片才能拿到，插件本身也做不到保存这些信息

兰空 V2 的删除 API

![20220327153441](https://cdn.dogimg.com/pic/2022/03/27/6240138e8d258.png)
> 兰空 V2 的删除 key 在每次上传成功图片时均会返回，但是插件本身也很难保存这些信息

我仔细思考后认为这个功能必要性不是很强，原作者的话对我有很大的影响：  
> 试想你用PicGo上传了一张图片放到某篇博客里，然后你在后来的某一天因为删除了相册导致远端的图片也被删除了，那么你的博客里的图片就等于丢了。这种情况是不是更危险呢？如果你说你用PicGo只是用来传图片，那么为啥不用一些其他上传工具来做这件事呢？PicGo的初衷是用来做图床上传的，既然是图床就要保证图片能公开访问，图片不会丢失外链。

但是这个功能应该还是可行的，虽然实现起来应该很麻烦，V1 和 V2 API 还不一样，暂时还请体谅一下。

**Comment by tonywang1201** [comment]
感谢您的回复。其实在这个版本的picgo中，我在picgo使用自带的github图床功能时是可以同步删除图片的，但实际使用起来，github的图床很慢，因此我自己搭建了lsky。

看了原作者的话，我觉得也挺有道理的，所以删除的功能暂时不能用也没事。但我有点不理解您“_实际上他的图片管理只是在本地进行数据的操作，默认不会同步到远端。_”这句话的意思。现在的情况下，在picgo中删除图片后，电脑本地和图床里的图片都还在。如果想删图片，只能在图床里删。但这样删除后，picgo里显示图片还在，图片多了容易混淆，错误的在编辑器中添加已经删除的图片。因此，如果以后有更新的计划，还是希望您能够测试一下删除的api。

总之，十分感谢您的付出。

**Comment by hellodk34** [comment]
> 实际上他的图片管理只是在本地进行数据的操作，默认不会同步到远端。

> 现在的情况下，在picgo中删除图片后，电脑本地和图床里的图片都还在。如果想删图片，只能在图床里删。但这样删除后，picgo里显示图片还在

PicGo 里删除了就没了啊，只是没有调用图床 API 删除远端图片。

**Comment by tonywang1201** [comment]
那我知道了，感谢您的回复

**Comment by hellodk34** [comment]
感谢你的建议，我抽空琢磨琢磨怎么实现，暂时关闭 issue 了。

**Comment by hellodk34** [comment]
@tonywang1201 已更新 `v1.0.5` 增加了同步删除的功能（仅 `V2`），接口可以调通，目前我发现是兰空图床程序有问题，无法通过接口删除图片。麻烦你也帮我测试一下。

**Comment by tonywang1201** [comment]
在勾选同步删除的情况下，我试了一下，picgo会弹出两条通知说图片已删除，但图床里的图片确实还在。

**Comment by hellodk34** [comment]
可以跟踪一下这个 [issue](https://github.com/lsky-org/lsky-pro/issues/366) 我也在检查这个问题。

**Comment by hellodk34** [comment]
@tonywang1201 @HalcyonAzure 

lankong 发布了 `v1.0.6` 版本，目前可以同步删除了（能从 web 上看出来）。特别感谢 @HalcyonAzure 帮忙测试。

Lsky Pro V2 源程序对于接口删除文件有个 **不能物理删除文件** 的 bug，截止目前作者已经修复。见 [此评论](https://github.com/lsky-org/lsky-pro/issues/366#issuecomment-1085572447)

目前很多兰空图床 V2 的站点应该都还没有更新到最新版，但是不影响 `lankong` 插件同步删除功能的使用。
