### ISSUE TITLE
请大家帮帮我吧 我实在是没办法了 关于图片上传失败

### ISSUE THREAD

**Issue by future5949** [hellodk34/picgo-plugin-lankong#21]
![248B275C-4A88-4808-95DC-0AF846EE95FD](https://user-images.githubusercontent.com/53705164/212372669-6b6b3813-8710-4451-a85b-082b7749badb.jpeg)
用的picgo lankong 1.1.3插件 插件配置均没问题（ip地址和token都已验证 我在局域网测试）可是无法通过picgo上传
目前问题说明
 1.我是用群晖webstion搭建的 可以通过网页上传图片并成功返回链接
2. 使用picgo插件可以成功上传到兰空官网的演示图床
自己猜想：
目前可以推测只能是服务端出了问题 可是我百思不得其解 为什么网页可以成功上传而picgo 却不行 难道是服务端的php扩展问题？请各位大神帮帮忙 谢谢了🙏

**Comment by hellodk34** [comment]
应该是本地搭建的服务端有问题，建议 google 一下参考别人在本地部署 Lsky Pro 的方法重新部署一个服务端，建议 docker 或者 docker-compose, 再尝试。

**Comment by future5949** [comment]
> 应该是本地搭建的服务端有问题，建议 google 一下参考别人在本地部署 Lsky Pro 的方法重新部署一个服务端，建议 docker 或者 docker-compose, 再尝试。

可是我买的企业版 没有docker版的……

**Comment by hellodk34** [comment]
> > 应该是本地搭建的服务端有问题，建议 google 一下参考别人在本地部署 Lsky Pro 的方法重新部署一个服务端，建议 docker 或者 docker-compose, 再尝试。
> 
> 可是我买的企业版 没有docker版的……

这个简单啊，docker hub 上搜一下不就有了。买的企业版是源码部署吧？用 docker 的话可以直接用别人构建好的镜像，比如我构建的 https://hub.docker.com/r/dko0/lsky-pro
