### ISSUE TITLE
Album ID设置无效

### ISSUE THREAD

**Issue by Potatoii** [hellodk34/picgo-plugin-lankong#25]
兰空图床版本:v2.1
picgo版本v2.3.1
我注意到兰空的upload接口没有相册id参数了，现在应该只有文件和储存策略ID两个参数可传

**Comment by hellodk34** [comment]
据我之前开发这个插件时候的了解，兰空图床的 album 形同虚设，没啥意义……  所以我就没怎么关注了。只要能上传图片到图床就行了，实际上把文件名命名好，后续在图片搜索那里还是能比较容易的去找到对应图片的。

但是兰空付费的那个版本，好像相册功能有所增强。

**Comment by Potatoii** [comment]
主要是markdown自动上传的图片一般不会看了，就想单独弄个相册存，但是既然api不支持相册id那也没办法了

**Comment by hellodk34** [comment]
兰空开源版这个功能确实有点弱。要不试试 https://github.com/icret/EasyImages2.0 体验一下看看（我还没体验过

**Comment by Icehomura** [comment]
这个问题我也遇到过，可以根据https://github.com/lsky-org/lsky-pro/issues/495修改ImageService.php解决

**Comment by hellodk34** [comment]
> 这个问题我也遇到过，可以根据 [lsky-org/lsky-pro#495](https://github.com/lsky-org/lsky-pro/issues/495) 修改ImageService.php解决

感谢指出
