### ISSUE TITLE
token生成问题求助

### ISSUE THREAD

**Issue by zui-lang** [hellodk34/picgo-plugin-lankong#28]
利用[toolscat](https://www.toolscat.com/dev/postman)，[sojson](https://www.sojson.com/http/test.html)等多个在线post生成token均提示页面不存在，请问是我的操作哪里有问题吗
![image](https://user-images.githubusercontent.com/77880495/235412019-f5f97fa4-5810-4eba-b684-da01d39874bf.jpeg)

**Comment by zui-lang** [comment]
不知道是ssl证书的问题还是nginx反向代理的问题，直接暴露端口http访问就可以生成了
Cloudflare的cdn也会阻挡token的生成

**Comment by zui-lang** [comment]
建议使用[Postman](https://postman.com)，经过vercel+Cloudflare双重代理后依旧可以生成token，缺点就是需要下载，并注册账号，操作有点繁琐

**Comment by hellodk34** [comment]
postman 太重，建议尝试一下 vscode 插件 `Thunder Client`。
