### ISSUE TITLE
删除函数中额外的JSON.parse导致报错

### ISSUE THREAD

**Issue by Kuingsmile** [hellodk34/picgo-plugin-lankong#32]
参考 https://github.com/Kuingsmile/PicList/issues/111

![image](https://github.com/hellodk34/picgo-plugin-lankong/assets/96409857/1df92f90-9efe-49da-b096-3a36988b48eb)

这里返回的body已经是对象了，不需要JSON.parse，在PicGo和我二次开发的PicList里都会报错，报错信息如下。经过测试可以直接注释掉第40行。

![image](https://github.com/hellodk34/picgo-plugin-lankong/assets/96409857/bfcedbc8-9efa-4c12-98bd-9847c9e09969)
![image](https://github.com/hellodk34/picgo-plugin-lankong/assets/96409857/53b72b75-3169-49f8-89c0-7da26d267c71)

**Comment by hellodk34** [comment]
没有测试过，你要不提 pr ?

**Comment by Kuingsmile** [comment]
> 没有测试过，你要不提 pr ?

#33

**Comment by hellodk34** [comment]
感谢提 pr
