### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by lianyant** [hellodk34/picgo-plugin-lankong#5]
请问大佬，当我选择的是腾讯云cos存储策略时，如何在typero软件上设置成 所插入的图片使用的是 上传到兰空图床的图片链接而不是使用的是存放到腾讯云cos中的图片链接呢？

![image-20220405234450570.png](https://pic.ysllw.com/i/2022/04/05/624c63f54c342.png)

自己一个一个的改的话很麻烦，因为我拿腾讯云cos也仅仅是做个备份，既然搭建了兰空图床的话，我就是希望能够直接使用兰空图床的图片链接，这样的话就不会消耗腾讯云cos的流量了。请问能够实现这一点吗？需要去哪里修改配置呢？   期待大佬的回复

并且我发现如果直接在picGo上传图片的话(且选择的也是腾讯云cos存储策略)，是直接能够得到兰空的图片链接，上面的这个问题的产生应该和 typera软件有关系吧？

**Comment by hellodk34** [comment]
你应该有一些误解。兰空图床只是一个能连接多种对象存储或者本地存储的图床前端程序，后台数据的存放是和具体的 `存储策略` 有关系的。既然你已经选择了使用腾讯云 cos 来存储图片，

> 既然搭建了兰空图床的话，我就是希望能够直接使用兰空图床的图片链接，这样的话就不会消耗腾讯云cos的流量了

你这样的想法是无法实现的。即使前端有个代理 url，但是实际上还是会消耗腾讯云 cos 的流量。而且这个和 typora 软件没有关系。

我记得 [cloudreve](http://cloudreve.org/) 会生成他自己的图片链接。但是实际上还是会消耗腾讯云 cos 的流量的哦。

**Comment by hellodk34** [comment]
> 因为我拿腾讯云cos也仅仅是做个备份，既然搭建了兰空图床的话，我就是希望能够直接使用兰空图床的图片链接  
> 并且我发现如果直接在picGo上传图片的话(且选择的也是腾讯云cos存储策略)，是直接能够得到兰空的图片链接

你的兰空图床有哪些存储策略？腾讯云 cos 是怎么备份的？通过 PicGo 上传图片时是默认的存储策略吗？

**Comment by lianyant** [comment]
> 

使用的是腾讯云cos存储策略，使用后，在配置好后你写的picgo插件后，能够实现上传图片到兰空图床时能够自动的也上传到腾讯云cos中，当然了typero软件中也能够使得插入的图片的连接自动转换为图床的Markdown链接，但是是转化为的是腾讯云的cos中的所对应的图片的Markdown链接，并不是直接转换为的兰空图床中所对应的那个图片的Markdown链接。  但是如果使用的是本地存储策略的话，那么直接转换为的就是兰空图床中所对应的那个图片的Markdown链接了。   其实这也没什么的，我自己对应着修改下就行了，不麻烦，我就是提出这一个现象吧！   还有就是大佬的脚本很好用。

**Comment by lianyant** [comment]
> 兰空图床只是一个连接对象存储或本地存储的前端程序，后台的数据选择是和具体的`存储策略`有关系的。图片，
> 
> > 直接的，就可以使用兰空图的图片链接
> 
> 即使最初的代理url，实际上还是会实现腾讯云的流量。而且这个和typora没有任何软件关系。
> 
> 我记得我记得[会](http://cloudreve.org/)生成他自己的图片链接但是。实际上还是会重新使用云会占用腾讯云的哦。

我换个问法吧，我去看到腾讯云cos中有这样一句话：“对象地址被访问后会产生请求及流量费用“。 那么我没有直接使用腾讯云cos对象的链接来在网络中访问图片的话，还是会收取流量费用吗(流量费用和对象存储的资源包不是同一个东西吧，你说的会产生费用是指的是资源包消耗的费用吗？)？还是说你的意思是指，相同的两张图片，我通过腾讯云cos存储策略，上传到了兰空图床，当然也同步上传到了一份到了腾讯云cos中，那么我仅仅在网络中以兰空图床中生成的该图片的链接来访问该图片 还是会消耗掉位于腾讯云cos中的该图片在网络中被访问所会产生的流量吗？               如果事实是这样的话，兰空图床设计出来腾讯云cos存储策略的目的又在哪里呢？

**Comment by hellodk34** [comment]
@lianyant 
> 如果事实是这样的话，兰空图床设计出来腾讯云cos存储策略的目的又在哪里呢？

假如你的兰空图床有个腾讯云 cos 的存储策略，你上传图片到这个存储上了，生成的图片链接是你兰空图床的 domain 还是腾讯云的 domain？

据我所知，兰空图床设计出来能够链接其他对象存储的意义是方便上传、删除、管理图片。而不是最传统的本地存储。这样兰空图床只是一个前端，兰空的程序封装了对象存储服务商的 api 然后提供了自己的一套 api 给终端用户。这比对象存储服务商的 api 好用（而且还有一个好看好用的 web page）

**Comment by lianyant** [comment]
@hellodk34 
假如你的兰空图床有个腾讯云 cos 的存储策略，你上传图片到这个存储上了，生成的图片链接是你兰空图床的 domain 还是腾讯云的 domain？
答：兰空图床中生成的是兰空的domain（不太明白domain的意思，反正兰空图床中使用腾讯云cos存储策略的话，传到兰空图床中的图片链接对应的是兰空图床的链接，不是腾讯云cos对应的图片链接。）。

还有之前的这个疑问：
疑问1：“对象地址被访问后会产生请求及流量费用“。 那么我没有直接使用腾讯云cos对象的链接来在网络中访问图片的话，还是会收取因为在网络中通过腾讯云cos中的图片链接来访问图片的流量费用吗？

疑问2：相同的两张图片，我通过腾讯云cos存储策略，上传到了兰空图床，当然也同步上传到了一份到了腾讯云cos中，那么我仅仅在网络中以兰空图床中生成的该图片的链接来访问该图片 还是会消耗掉位于腾讯云cos中的该图片在网络中被访问所会产生的流量吗？

**Comment by hellodk34** [comment]
@lianyant 不好意思啊，因为我没有备案过的域名，所以我都没有用过国内的对象存储服务。我的意思是，如果你用了腾讯云 cos 的存储策略，图片经过兰空图床上传之后生成的图片直链（direct link）是怎样的，域名是你自己的还是腾讯的？

> 比如一个 markdown style 的链接 ![xxx.png](https://lsky.example.com/i/xxx.png)

这个图片直链是你自己的域名还是腾讯的。

### 回疑问 1

答：如果访问的直链不是腾讯云的可能不会收取流量，因为别人已经帮你缓存了一份。

### 回疑问 2

答：和上面疑问 1 类似，如果被缓存了一份，应该不会收取腾讯云的流量了，只会计算你搭建兰空图床的 vps 的流量。

**Comment by lianyant** [comment]
@hellodk34 
用了腾讯云 cos 的存储策略，图片经过兰空图床上传之后生成的图片直链（direct link）是我兰空图床的域名所对应的markdown图片链接，域名是我自己的（也就是我所搭建的兰空图床的域名）。


好的，谢谢你的解答！  我的疑问解决了

**Comment by hellodk34** [comment]
@lianyant 客气了。

**Comment by hellodk34** [comment]
回复你最开始的疑问，这应该是 Typora 导致的，也不太好解决，既然 PicGo 能解决那么就用 PicGo 上传图片然后贴到 Typora 吧。这样就不会一直消耗腾讯云 cos 的流量了。 @lianyant

**Comment by lianyant** [comment]
好的，再次感谢！
@hellodk34
