### ISSUE TITLE
请问怎么使用 Bearer 拼接拿到token

### ISSUE THREAD

**Issue by DAMYSDS** [hellodk34/picgo-plugin-lankong#6]
请求成功后得到返回信息中的 token，使用 Bearer 拼接拿到的 token 作为 Auth token 
已经拿到了第一个 token，怎么使用 Bearer 拼接拿到的 token，我用的postman

**Comment by hellodk34** [comment]
@DAMYSDS  就是字符串拼接。

假如你通过 postman 拿到的 token 是 `56|ahssCFsdfsksdfsdfsdfsdf` 那么 `Auth token` 里就填写 `Bearer 56|ahssCFsdfsksdfsdfsdfsdf` 就好了。（我试过 Bearer 后面跟上两个空格都没关系，一样可以通过认证，不过一般是一个空格）

**Comment by hellodk34** [comment]
看一下你使用的图床的 api 文档，如下图，有介绍的。

![20220418091059](https://img.github.luxe/2022/4dce463144f29.png)
