### ISSUE TITLE
希望更改插件配置Sever的一些描述

### ISSUE THREAD

**Issue by Goojoe** [hellodk34/picgo-plugin-lankong#7]
因为我之前用的是lskypro1.0的官方插件,我一直以为是
`https://domain.com/api/upload`
结果就是报错,我才发现`https://domain.com`才是正确的

所以请写个注意不是官方PicGo插件lskypro1.0
`https://domain.com/api/upload`
注意删除后面的`/api/upload/`,以防混淆
V2也是一样的
最后感谢你为Lskypro 2.0做适配

**Comment by hellodk34** [comment]
@Goojoe 项目 README 中有如下的描述

> 填写图床的 `server url`，注意不要以 `/` 结束，比如 `https://example.com` 就是没问题的

感觉这应该足够了吧如果仔细阅读了项目 readme 应该不会出错，填写的是 Server Url 并不是 api url。当然了这段描述可以优化，感谢建议。
