### ISSUE TITLE
picgo 上传404 页面不存在

### ISSUE THREAD

**Issue by lovebetterworld** [hellodk34/picgo-plugin-lankong#9]
我用APIPost接口方式测试图片上传没用问题，但是使用Picgo上传，上传不上去。
告诉我404，页面不存在，都是同一个接口，哪里有问题吗？

**Comment by lovebetterworld** [comment]
StatusCodeError: 404 - "<!DOCTYPE html>\n<html lang=\"en\">\n    <head>\n        <meta charset=\"utf-8\">\n        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n\n        <title>页面不存在</title>\n\n        <style>\n            /*! normalize.css v8.0.1 | MIT License | github.com/necolas/normalize.css */html{line-height:1.15;-webkit-text-size-adjust:100%}body{margin:0}a{background-color:transparent}code{font-family:monospace,monospace;font-size:1em}[hidden]{display:none}html{font-family:system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji;line-height:1.5}*,:after,:before{box-sizing:border-box;border:0 solid #e2e8f0}a{color:inherit;text-decoration:inherit}code{font-family:Menlo,Monaco,Consolas,Liberation Mono,Courier New,monospace}svg,video{display:block;vertical-align:middle}video{max-width:100%;height:auto}.bg-white{--bg-opacity:1;background-color:#fff;background-color:rgba(255,255,255,var(--bg-opacity))}.bg-gray-100{--bg-opacity:1;background-color:#f7fafc;background-color:rgba(247,250,252,var(--bg-opacity))}.border-gray-200{--border-opacity:1;border-color:#edf2f7;border-color:rgba(237,242,247,var(--border-opacity))}.border-gray-400{--border-opacity:1;border-color:#cbd5e0;border-color:rgba(203,213,224,var(--border-opacity))}.border-t{border-top-width:1px}.border-r{border-right-width:1px}.flex{display:flex}.grid{display:grid}.hidden{display:none}.items-center{align-items:center}.justify-center{justify-content:center}.font-semibold{font-weight:600}.h-5{height:1.25rem}.h-8{height:2rem}.h-16{height:4rem}.text-sm{font-size:.875rem}.text-lg{font-size:1.125rem}.leading-7{line-height:1.75rem}.mx-auto{margin-left:auto;margin-right:auto}.ml-1{margin-left:.25rem}.mt-2{margin-top:.5rem}.mr-2{margin-right:.5rem}.ml-2{margin-left:.5rem}.mt-4{margin-top:1rem}.ml-4{margin-left:1rem}.mt-8{margin-top:2rem}.ml-12{margin-left:3rem}.-mt-px{margin-top:-1px}.max-w-xl{max-width:36rem}.max-w-6xl{max-width:72rem}.min-h-screen{min-height:100vh}.overflow-hidden{overflow:hidden}.p-6{padding:1.5rem}.py-4{padding-top:1rem;padding-bottom:1rem}.px-4{padding-left:1rem;padding-right:1rem}.px-6{padding-left:1.5rem;padding-right:1.5rem}.pt-8{padding-top:2rem}.fixed{position:fixed}.relative{position:relative}.top-0{top:0}.right-0{right:0}.shadow{box-shadow:0 1px 3px 0 rgba(0,0,0,.1),0 1px 2px 0 rgba(0,0,0,.06)}.text-center{text-align:center}.text-gray-200{--text-opacity:1;color:#edf2f7;color:rgba(237,242,247,var(--text-opacity))}.text-gray-300{--text-opacity:1;color:#e2e8f0;color:rgba(226,232,240,var(--text-opacity))}.text-gray-400{--text-opacity:1;color:#cbd5e0;color:rgba(203,213,224,var(--text-opacity))}.text-gray-500{--text-opacity:1;color:#a0aec0;color:rgba(160,174,192,var(--text-opacity))}.text-gray-600{--text-opacity:1;color:#718096;color:rgba(113,128,150,var(--text-opacity))}.text-gray-700{--text-opacity:1;color:#4a5568;color:rgba(74,85,104,var(--text-opacity))}.text-gray-900{--text-opacity:1;color:#1a202c;color:rgba(26,32,44,var(--text-opacity))}.uppercase{text-transform:uppercase}.underline{text-decoration:underline}.antialiased{-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale}.tracking-wider{letter-spacing:.05em}.w-5{width:1.25rem}.w-8{width:2rem}.w-auto{width:auto}.grid-cols-1{grid-template-columns:repeat(1,minmax(0,1fr))}@-webkit-keyframes spin{0%{transform:rotate(0deg)}to{transform:rotate(1turn)}}@keyframes  spin{0%{transform:rotate(0deg)}to{transform:rotate(1turn)}}@-webkit-keyframes ping{0%{transform:scale(1);opacity:1}75%,to{transform:scale(2);opacity:0}}@keyframes  ping{0%{transform:scale(1);opacity:1}75%,to{transform:scale(2);opacity:0}}@-webkit-keyframes pulse{0%,to{opacity:1}50%{opacity:.5}}@keyframes  pulse{0%,to{opacity:1}50%{opacity:.5}}@-webkit-keyframes bounce{0%,to{transform:translateY(-25%);-webkit-animation-timing-function:cubic-bezier(.8,0,1,1);animation-timing-function:cubic-bezier(.8,0,1,1)}50%{transform:translateY(0);-webkit-animation-timing-function:cubic-bezier(0,0,.2,1);animation-timing-function:cubic-bezier(0,0,.2,1)}}@keyframes  bounce{0%,to{transform:translateY(-25%);-webkit-animation-timing-function:cubic-bezier(.8,0,1,1);animation-timing-function:cubic-bezier(.8,0,1,1)}50%{transform:translateY(0);-webkit-animation-timing-function:cubic-bezier(0,0,.2,1);animation-timing-function:cubic-bezier(0,0,.2,1)}}@media (min-width:640px){.sm\\:rounded-lg{border-radius:.5rem}.sm\\:block{display:block}.sm\\:items-center{align-items:center}.sm\\:justify-start{justify-content:flex-start}.sm\\:justify-between{justify-content:space-between}.sm\\:h-20{height:5rem}.sm\\:ml-0{margin-left:0}.sm\\:px-6{padding-left:1.5rem;padding-right:1.5rem}.sm\\:pt-0{padding-top:0}.sm\\:text-left{text-align:left}.sm\\:text-right{text-align:right}}@media (min-width:768px){.md\\:border-t-0{border-top-width:0}.md\\:border-l{border-left-width:1px}.md\\:grid-cols-2{grid-template-columns:repeat(2,minmax(0,1fr))}}@media (min-width:1024px){.lg\\:px-8{padding-left:2rem;padding-right:2rem}}@media (prefers-color-scheme:dark){.dark\\:bg-gray-800{--bg-opacity:1;background-color:#2d3748;background-color:rgba(45,55,72,var(--bg-opacity))}.dark\\:bg-gray-900{--bg-opacity:1;background-color:#1a202c;background-color:rgba(26,32,44,var(--bg-opacity))}.dark\\:border-gray-700{--border-opacity:1;border-color:#4a5568;border-color:rgba(74,85,104,var(--border-opacity))}.dark\\:text-white{--text-opacity:1;color:#fff;color:rgba(255,255,255,var(--text-opacity))}.dark\\:text-gray-400{--text-opacity:1;color:#cbd5e0;color:rgba(203,213,224,var(--text-opacity))}}\n        </style>\n\n        <style>\n            body {\n                font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, \"Noto Sans\", sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\", \"Noto Color Emoji\";\n            }\n        </style>\n    </head>\n    <body class=\"antialiased\">\n        <div class=\"relative flex items-top justify-center min-h-screen bg-gray-100 dark:bg-gray-900 sm:items-center sm:pt-0\">\n            <div class=\"max-w-xl mx-auto sm:px-6 lg:px-8\">\n                <div class=\"flex items-center pt-8 sm:justify-start sm:pt-0\">\n                    <div class=\"px-4 text-lg text-gray-500 border-r border-gray-400 tracking-wider\">\n                        404                    </div>\n\n                    <div class=\"ml-4 text-lg text-gray-500 uppercase tracking-wider\">\n                        页面不存在                    </div>\n                </div>\n            </div>\n        </div>\n    </body>\n</html>\n"
    at new StatusCodeError (E:\picgo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (E:\picgo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (E:\picgo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (E:\picgo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (E:\picgo\resources\app.asar\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (E:\picgo\resources\app.asar\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End-------

**Comment by hellodk34** [comment]
贴一下你 PicGo `lankong` 插件配置的图看看

**Comment by hellodk34** [comment]
仔细看过本项目的 README 没有？ `server url` 不要填成了 `api url`

**Comment by lovebetterworld** [comment]
我的端口，不是默认的，我改成8443了。
404

**Comment by lovebetterworld** [comment]
已解决，版本问题，选成了V1

**Comment by lovebetterworld** [comment]
用接口方式测试了下，
"links": {
			"url": "http://49.232.217.155:8090/i/2022/04/25/6265fe19b87d9.png",
			"html": "&lt;img src=\"http://49.232.217.155:8090/i/2022/04/25/6265fe19b87d9.png\" alt=\"Sni20220425094835.png\" title=\"Sni20220425094835.png\" /&gt;",
			"bbcode": "[img]http://49.232.217.155:8090/i/2022/04/25/6265fe19b87d9.png[/img]",
			"markdown": "![Sni20220425094835.png](http://49.232.217.155:8090/i/2022/04/25/6265fe19b87d9.png)",
			"markdown_with_link": "[![Sni20220425094835.png](http://49.232.217.155:8090/i/2022/04/25/6265fe19b87d9.png)](http://49.232.217.155:8090/i/2022/04/25/6265fe19b87d9.png)",
			"thumbnail_url": "https://www.lovebetterworld.com:8443/thumbnails/e5849981ef4aa01ace3ab38379150811.png"
		}

thumbnail_url的结果可以。

**Comment by hellodk34** [comment]
@lovebetterworld  用 Typora + PicGo 的工作流我没有试过。能不能介绍下你的 flow 是啥样的？我平时都是复制图片，键盘按 Control + Shift + P，然后上传成功，PicGo 自动把 markdown style 的地址写入系统剪贴板，我直接在 vscode 中粘贴。返回的 URL 是域名。

**Comment by lovebetterworld** [comment]
嗯，我用的截图工具是Snipaste，图片压缩或裁剪工具的话，utools里的插件。
1：配置Typora的PicGo插件，
![image](https://user-images.githubusercontent.com/26848424/165010438-63206372-a922-4db8-a1de-bc1178fda6e7.png)

2：通过Snipaste截图后，直接在Typora编辑器里粘贴下，会自动上传图片。

我试了下，返回的URL是http://ip 的，既不是https，也没有带域名，不知道是不是哪里设置的问题。

**Comment by hellodk34** [comment]
PicGo `lankong` 插件的配置是怎样的？（你可以把域名和 token 都打码）

**Comment by lovebetterworld** [comment]
![image](https://user-images.githubusercontent.com/26848424/165010796-a3e2bdfe-db02-4f9a-b366-69efb887bac2.png)

**Comment by hellodk34** [comment]
你 Typora 里有个设定 `插入时自动转义图片 URL`，也看看是不是这些 Typora 软件的设置导致的

**Comment by lovebetterworld** [comment]
我刚试了，通过PicGo上传上去，返回的URL也不对。

**Comment by hellodk34** [comment]
> 通过Snipaste截图后，直接在Typora编辑器里粘贴下，会自动上传图片。

你这肯定是 Typora 干预导致的问题。

**Comment by lovebetterworld** [comment]
我没有用Typora，直接用PicGo，复制图片，然后Ctrl+Shift+p，上传上去，粘贴出来的URL也是http://ip的形式哈。哪里配置有问题吗？

**Comment by hellodk34** [comment]
@lovebetterworld 
> 我没有用Typora，直接用PicGo，复制图片，然后Ctrl+Shift+p，上传上去，粘贴出来的URL也是 http://ip 的形式哈。哪里配置有问题吗？

这个我估计是你 Lsky Pro 图床设置的问题。你看一下存储策略的设置 （路径是 `系统` -> `存储策略` url like `https://example.com/admin/strategies/1`），看一下 `访问网址` 是域名还是 IP？

**Comment by lovebetterworld** [comment]
![image](https://user-images.githubusercontent.com/26848424/165012946-9ebf7520-7840-4405-b9cb-63f0d2fe540f.png)

**Comment by lovebetterworld** [comment]
我访问网址的话，是域名的形式。

**Comment by hellodk34** [comment]
![20220425110232](https://pic.dogimg.com/2022/04/25/62660f64ab5c6.png)

我的是这样的，正常使用。你这个现象再看看是不是 nginx 问题？通过 web 能上传成功吗，打开图片查看详情复制一下 URL 呢？

另外你可能限制了 source ip，我无法访问你的 Lsky Pro 站点。

**Comment by lovebetterworld** [comment]
通过Web上传，没有问题，图片URL是https://域名的形式。
嗯嗯嗯，Lsky Pro的安全组我没放开，外网可能访问不了。
nginx，嗯，nginx只是做了个反向代理，还有其他配置吗？

**Comment by hellodk34** [comment]
@lovebetterworld 通过 tg 联系我吧 `aHR0cHM6Ly90Lm1lL2tveHhvawo=` (base64 encoded, decode it to get original string)

**Comment by lovebetterworld** [comment]
decode后，一个https地址？

**Comment by lovebetterworld** [comment]
冒昧问下tg是？

**Comment by hellodk34** [comment]
嗯，看来你不用这个。tg 是 Telegram。

你这个问题应该不是 lankong 插件导致的，不过可以加我微信 (`ZGtrYWxsCg==`) 我和你一起探讨下。
